In [5]:
import pandas as pd
import numpy as np

In [6]:
emergent = pd.read_csv('..\data\emergent\url-versions-2015-06-14-clean.csv')
emergent_transformed = pd.read_csv('mscproject\data\emergent\Emergent_features.csv')

#I got the second csv above by running get_data() from features.py() on ..\data\emergent\url-versions-2015-06-14-clean.csv'

In [7]:
emergent_transformed.head()

,0,1,2,3,4,5,6,7,8,9,...,508,509,510,511,512,513,514,515,516,517
0,0.209241,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0
1,-0.040564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0
2,-0.028938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,100.0,100.0,0.0
3,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,100.0,100.0,1.0
4,0.002010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,100.0,2.0,0.0

In [8]:
emergent_transformed['articleHeadlineStance'] = emergent['articleHeadlineStance']

In [10]:
emergent_transformed.head()

,0,1,2,3,4,5,6,7,8,9,...,509,510,511,512,513,514,515,516,517,articleHeadlineStance
0,0.209241,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,observing
1,-0.040564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,100.0,100.0,0.0,for
2,-0.028938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,100.0,100.0,0.0,for
3,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,100.0,100.0,1.0,for
4,0.002010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,100.0,2.0,0.0,for

In [13]:
emergent_transformed.to_csv('mscproject/data/emergent/Emergent_features_and_labels.csv')